import "../globals.css";
import { Poppins, Oswald } from "next/font/google";
import Header from "@/components/Header/Header.jsx";

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["300", "400", "700"],
  variable: "--font-poppins"
});

const oswald = Oswald({ 
  subsets: ["latin"], 
  weight: ["300", "400", "700"],
  variable: "--font-oswald"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
  <body 
    className={`${poppins.variable} ${oswald.variable}`} 
    style={{
      paddingTop: "100px", 
      background: "linear-gradient(to right, #FDB246, #FE6F02)"
    }} 
  >
    <Header />
    {children}
  </body>
</html>

  );
}
